-- Remplace les options de la dimension Couleur du produit PIGMENT2KG
-- par la liste complète des teintes RAL standards (idem FLOWCOATPD / QuartzColor)
-- Les labels "RAL XXXX" sont rendus automatiquement comme pastilles de couleur
-- via getRalInfo() dans VarianteSelect.tsx (ralColors.ts)

UPDATE public.produits
SET variantes = (
  SELECT jsonb_agg(
    CASE
      WHEN (dim->'options')::text ILIKE '%RAL 1023%'
      THEN jsonb_set(dim, '{options}', jsonb_build_array(
        jsonb_build_object('label', 'RAL 1000', 'prixDiff', 0),
        jsonb_build_object('label', 'RAL 1001', 'prixDiff', 0),
        jsonb_build_object('label', 'RAL 1002', 'prixDiff', 0),
        jsonb_build_object('label', 'RAL 1003', 'prixDiff', 0),
        jsonb_build_object('label', 'RAL 1004', 'prixDiff', 0),
        jsonb_build_object('label', 'RAL 1007', 'prixDiff', 0),
        jsonb_build_object('label', 'RAL 1011', 'prixDiff', 0),
        jsonb_build_object('label', 'RAL 1013', 'prixDiff', 0),
        jsonb_build_object('label', 'RAL 1014', 'prixDiff', 0),
        jsonb_build_object('label', 'RAL 1015', 'prixDiff', 0),
        jsonb_build_object('label', 'RAL 1016', 'prixDiff', 0),
        jsonb_build_object('label', 'RAL 1018', 'prixDiff', 0),
        jsonb_build_object('label', 'RAL 1021', 'prixDiff', 0),
        jsonb_build_object('label', 'RAL 1023', 'prixDiff', 0),
        jsonb_build_object('label', 'RAL 1028', 'prixDiff', 0),
        jsonb_build_object('label', 'RAL 2000', 'prixDiff', 0),
        jsonb_build_object('label', 'RAL 2001', 'prixDiff', 0),
        jsonb_build_object('label', 'RAL 2003', 'prixDiff', 0),
        jsonb_build_object('label', 'RAL 2004', 'prixDiff', 0),
        jsonb_build_object('label', 'RAL 2009', 'prixDiff', 0),
        jsonb_build_object('label', 'RAL 3000', 'prixDiff', 0),
        jsonb_build_object('label', 'RAL 3001', 'prixDiff', 0),
        jsonb_build_object('label', 'RAL 3002', 'prixDiff', 0),
        jsonb_build_object('label', 'RAL 3003', 'prixDiff', 0),
        jsonb_build_object('label', 'RAL 3005', 'prixDiff', 0),
        jsonb_build_object('label', 'RAL 3009', 'prixDiff', 0),
        jsonb_build_object('label', 'RAL 3011', 'prixDiff', 0),
        jsonb_build_object('label', 'RAL 3013', 'prixDiff', 0),
        jsonb_build_object('label', 'RAL 3016', 'prixDiff', 0),
        jsonb_build_object('label', 'RAL 3020', 'prixDiff', 0),
        jsonb_build_object('label', 'RAL 3027', 'prixDiff', 0),
        jsonb_build_object('label', 'RAL 4001', 'prixDiff', 0),
        jsonb_build_object('label', 'RAL 4002', 'prixDiff', 0),
        jsonb_build_object('label', 'RAL 4003', 'prixDiff', 0),
        jsonb_build_object('label', 'RAL 4005', 'prixDiff', 0),
        jsonb_build_object('label', 'RAL 4006', 'prixDiff', 0),
        jsonb_build_object('label', 'RAL 5000', 'prixDiff', 0),
        jsonb_build_object('label', 'RAL 5002', 'prixDiff', 0),
        jsonb_build_object('label', 'RAL 5003', 'prixDiff', 0),
        jsonb_build_object('label', 'RAL 5005', 'prixDiff', 0),
        jsonb_build_object('label', 'RAL 5007', 'prixDiff', 0),
        jsonb_build_object('label', 'RAL 5010', 'prixDiff', 0),
        jsonb_build_object('label', 'RAL 5012', 'prixDiff', 0),
        jsonb_build_object('label', 'RAL 5013', 'prixDiff', 0),
        jsonb_build_object('label', 'RAL 5015', 'prixDiff', 0),
        jsonb_build_object('label', 'RAL 5017', 'prixDiff', 0),
        jsonb_build_object('label', 'RAL 5019', 'prixDiff', 0),
        jsonb_build_object('label', 'RAL 5021', 'prixDiff', 0),
        jsonb_build_object('label', 'RAL 5024', 'prixDiff', 0),
        jsonb_build_object('label', 'RAL 6000', 'prixDiff', 0),
        jsonb_build_object('label', 'RAL 6001', 'prixDiff', 0),
        jsonb_build_object('label', 'RAL 6002', 'prixDiff', 0),
        jsonb_build_object('label', 'RAL 6003', 'prixDiff', 0),
        jsonb_build_object('label', 'RAL 6005', 'prixDiff', 0),
        jsonb_build_object('label', 'RAL 6009', 'prixDiff', 0),
        jsonb_build_object('label', 'RAL 6010', 'prixDiff', 0),
        jsonb_build_object('label', 'RAL 6011', 'prixDiff', 0),
        jsonb_build_object('label', 'RAL 6016', 'prixDiff', 0),
        jsonb_build_object('label', 'RAL 6017', 'prixDiff', 0),
        jsonb_build_object('label', 'RAL 6018', 'prixDiff', 0),
        jsonb_build_object('label', 'RAL 6024', 'prixDiff', 0),
        jsonb_build_object('label', 'RAL 7000', 'prixDiff', 0),
        jsonb_build_object('label', 'RAL 7001', 'prixDiff', 0),
        jsonb_build_object('label', 'RAL 7004', 'prixDiff', 0),
        jsonb_build_object('label', 'RAL 7005', 'prixDiff', 0),
        jsonb_build_object('label', 'RAL 7011', 'prixDiff', 0),
        jsonb_build_object('label', 'RAL 7015', 'prixDiff', 0),
        jsonb_build_object('label', 'RAL 7016', 'prixDiff', 0),
        jsonb_build_object('label', 'RAL 7021', 'prixDiff', 0),
        jsonb_build_object('label', 'RAL 7022', 'prixDiff', 0),
        jsonb_build_object('label', 'RAL 7024', 'prixDiff', 0),
        jsonb_build_object('label', 'RAL 7030', 'prixDiff', 0),
        jsonb_build_object('label', 'RAL 7032', 'prixDiff', 0),
        jsonb_build_object('label', 'RAL 7035', 'prixDiff', 0),
        jsonb_build_object('label', 'RAL 7037', 'prixDiff', 0),
        jsonb_build_object('label', 'RAL 7038', 'prixDiff', 0),
        jsonb_build_object('label', 'RAL 7039', 'prixDiff', 0),
        jsonb_build_object('label', 'RAL 7040', 'prixDiff', 0),
        jsonb_build_object('label', 'RAL 7042', 'prixDiff', 0),
        jsonb_build_object('label', 'RAL 7043', 'prixDiff', 0),
        jsonb_build_object('label', 'RAL 7044', 'prixDiff', 0),
        jsonb_build_object('label', 'RAL 7045', 'prixDiff', 0),
        jsonb_build_object('label', 'RAL 7047', 'prixDiff', 0),
        jsonb_build_object('label', 'RAL 8001', 'prixDiff', 0),
        jsonb_build_object('label', 'RAL 8003', 'prixDiff', 0),
        jsonb_build_object('label', 'RAL 8004', 'prixDiff', 0),
        jsonb_build_object('label', 'RAL 8007', 'prixDiff', 0),
        jsonb_build_object('label', 'RAL 8008', 'prixDiff', 0),
        jsonb_build_object('label', 'RAL 8011', 'prixDiff', 0),
        jsonb_build_object('label', 'RAL 8012', 'prixDiff', 0),
        jsonb_build_object('label', 'RAL 8014', 'prixDiff', 0),
        jsonb_build_object('label', 'RAL 8017', 'prixDiff', 0),
        jsonb_build_object('label', 'RAL 8019', 'prixDiff', 0),
        jsonb_build_object('label', 'RAL 8022', 'prixDiff', 0),
        jsonb_build_object('label', 'RAL 8023', 'prixDiff', 0),
        jsonb_build_object('label', 'RAL 9001', 'prixDiff', 0),
        jsonb_build_object('label', 'RAL 9002', 'prixDiff', 0),
        jsonb_build_object('label', 'RAL 9003', 'prixDiff', 0),
        jsonb_build_object('label', 'RAL 9004', 'prixDiff', 0),
        jsonb_build_object('label', 'RAL 9005', 'prixDiff', 0),
        jsonb_build_object('label', 'RAL 9006', 'prixDiff', 0),
        jsonb_build_object('label', 'RAL 9007', 'prixDiff', 0),
        jsonb_build_object('label', 'RAL 9010', 'prixDiff', 0),
        jsonb_build_object('label', 'RAL 9011', 'prixDiff', 0),
        jsonb_build_object('label', 'RAL 9016', 'prixDiff', 0),
        jsonb_build_object('label', 'RAL 9018', 'prixDiff', 0),
        jsonb_build_object('label', 'RAL 9022', 'prixDiff', 0),
        jsonb_build_object('label', 'RAL 9023', 'prixDiff', 0)
      ))
      ELSE dim
    END
  )
  FROM jsonb_array_elements(variantes) AS dim
)
WHERE reference = 'PIGMENT2KG';
